spring:
  profiles:
    include:
      - oauth
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver

  h2.console.enabled: true

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace